kind: Deployment
apiVersion: apps/v1
metadata:
    name: edu_abc_tech
spec:
    replicas: 2
    minReadySeconds: 45
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: edu_abc_tech
    template:
        metadata:
            labels:
                app: edu_abc_tech
        spec:
            containers:
                - image: iambowcreek/edu_abc_tech:latest
                  name: app
---

kind: Service
apiVersion: v1
metadata:
    name: edu_abc_tech
spec:
    type: NodePort
    selector:
        app: edu_abc_tech
    ports:
        - port: 80 #cluster port
          targetPort: 8080 #container image port